### PR TITLE
Integrated tab expansion

### PR DESCRIPTION
**Pull request by chKarner**
Great work!

The only thing missing for me was some kind of tab expansion. 
You can pull if you want.

### CODE REVIEW

**Comment by manojlds** [comment]
Thanks for taking the time! I tried out the tab expansion, but it doesn't work for me ( maybe I am on Powershell 3.0? )

I will look into it in a few days and pull it in.

Thanks again!

**Comment by chKarner** [comment]
My fault, i was using a function that was provided by posh-git...

I still have to test if it works on Powershell 3.0

**Comment by manojlds** [comment]
@chKarner - still working on this? :) Is this something I should review and merge?

**Comment by chKarner** [comment]
I forgot that the pull request is still open. ;)

I did a major rewrite of the ranking a while ago, so im not sure if it is a good idea to merge.
(Works well for me though.)

I think the best action is to close the pull request.

**Pull request closed without merging**
